"""Interval detection data: names and reference melodies."""

INTERVAL_NAMES = {
    "es": {
        0: "Unísono justo",
        1: "Segunda menor",
        2: "Segunda mayor",
        3: "Tercera menor",
        4: "Tercera mayor",
        5: "Cuarta justa",
        6: "Cuarta aum. / Quinta dim.",
        7: "Quinta justa",
        8: "Sexta menor",
        9: "Sexta mayor",
        10: "Séptima menor",
        11: "Séptima mayor",
        12: "Octava justa",
    },
    "en": {
        0: "Perfect Unison",
        1: "Minor Second",
        2: "Major Second",
        3: "Minor Third",
        4: "Major Third",
        5: "Perfect Fourth",
        6: "Aug. Fourth / Dim. Fifth",
        7: "Perfect Fifth",
        8: "Minor Sixth",
        9: "Major Sixth",
        10: "Minor Seventh",
        11: "Major Seventh",
        12: "Perfect Octave",
    },
}

# Enharmonic alternative names per semitone (excluding the main name in
# INTERVAL_NAMES). Not every semitone count has a common alternative.
INTERVAL_ALT_NAMES = {
    "es": {
        0: ["Segunda disminuida"],
        1: ["Unísono aumentado"],
        2: ["Tercera disminuida"],
        3: ["Segunda aumentada"],
        4: ["Cuarta disminuida"],
        5: ["Tercera aumentada"],
        6: ["Tritono"],
        7: ["Sexta disminuida"],
        8: ["Quinta aumentada"],
        9: ["Séptima disminuida"],
        10: ["Sexta aumentada"],
        11: ["Octava disminuida"],
        12: ["Séptima aumentada"],
    },
    "en": {
        0: ["Diminished Second"],
        1: ["Augmented Unison"],
        2: ["Diminished Third"],
        3: ["Augmented Second"],
        4: ["Diminished Fourth"],
        5: ["Augmented Third"],
        6: ["Tritone"],
        7: ["Diminished Sixth"],
        8: ["Augmented Fifth"],
        9: ["Diminished Seventh"],
        10: ["Augmented Sixth"],
        11: ["Diminished Octave"],
        12: ["Augmented Seventh"],
    },
}

# Duration codes: w=redonda h=blanca q=negra e=corchea s=semicorchea
# Add "." for dotted. null=rest
# jumpAt: index where the interval occurs (default 0 = jump between notes 0 and 1)
INTERVAL_MELODIES = {
    1: {
        "name_es": "Tiburón (Jaws)",
        "name_en": "Jaws Theme",
        "beats_per_bar": 4,
        "show_full": True,
        "accent": True,
        "offsets": [0, 1, 0, 1, 0, 1, 0, 1],
        "durations": ["e", "e", "e", "e", "e", "e", "e", "e"],
    },
    2: {
        "name_es": "Cumpleaños feliz",
        "name_en": "Happy Birthday",
        "beats_per_bar": 3,
        "anacrusis": 1,
        "jump_at": 1,
        "offsets": [0, 0, 2, 0, 5, 4],
        "durations": ["e.", "s", "q", "q", "q", "h"],
    },
    3: {
        "name_es": "Smoke on the Water",
        "name_en": "Smoke on the Water",
        "beats_per_bar": 4,
        "offsets": [0, 3, 5, None, 0, None, 3, 6, 5],
        "durations": ["q", "q", "q", "e", "e", "e", "q", "e", "h"],
    },
    4: {
        "name_es": "When the Saints Go Marching In",
        "name_en": "When the Saints Go Marching In",
        "beats_per_bar": 4,
        "anacrusis": 1,
        "playback_step_ms": 320,
        "offsets": [0, 4, 5, 7],
        "durations": ["q", "q", "q", "w"],
    },
    5: {
        "name_es": "Here Comes the Bride",
        "name_en": "Here Comes the Bride",
        "beats_per_bar": 4,
        "jump_at": 3,
        "setup_slur": False,
        "highlight_until": 1,
        "offsets": [0, 5, 5, 5, 0, 7, 4, 5],
        "durations": ["q", "e.", "s", "h", "q", "e.", "s", "h"],
    },
    6: {
        "name_es": "María (West Side Story)",
        "name_en": "Maria (West Side Story)",
        "beats_per_bar": 3,
        "setup_slur": False,
        "offsets": [0, 6, 7, 4, 0, -5],
        "durations": ["q.", "e", "h", "q", "q", "h"],
    },
    7: {
        "name_es": "Star Wars",
        "name_en": "Star Wars",
        "beats_per_bar": 4,
        "offsets": [0, 7, 5, 4, 2, 12, 7],
        "durations": ["h", "h", "et", "et", "et", "h", "q"],
    },
    8: {
        "name_es": "Love Story",
        "name_en": "Love Story",
        "beats_per_bar": 4,
        "anacrusis": 1,
        "playback_step_ms": 520,
        "highlight_until": 2,
        "offsets": [0, 0, 8, 8, 0, 1, 0, -2],
        "durations": ["e", "e", "e", "e", "e", "e", "e", "e"],
    },
    9: {
        "name_es": "My Way",
        "name_en": "My Way",
        "beats_per_bar": 4,
        "anacrusis": 1.5,
        "offsets": [0, 9, 7, 9],
        "durations": ["e", "e", "e", "h"],
    },
    10: {
        "name_es": "Somewhere (West Side Story)",
        "name_en": "Somewhere (West Side Story)",
        "beats_per_bar": 4,
        "offsets": [0, 10, 9, 5, 2],
        "durations": ["h", "h", "q.", "e", "h"],
    },
    11: {
        "name_es": "Take On Me",
        "name_en": "Take On Me",
        "beats_per_bar": 4,
        "offsets": [0, 11, 12],
        "durations": ["h", "h", "h"],
    },
    12: {
        "name_es": "Somewhere Over the Rainbow",
        "name_en": "Somewhere Over the Rainbow",
        "beats_per_bar": 4,
        "offsets": [0, 12, 11, 7, 9, 11, 12],
        "durations": ["h", "h", "q", "e", "e", "q", "q"],
    },
}
